### ISSUE TITLE
New version using graphql-core-next instead of graphql-core

### ISSUE THREAD

**Issue by Cito** [graphql-python/graphql-server#20]
We should create a version that uses graphql-core-next instead of graphql-core.

@norman-thomas has already created PR #17 for this and I have also created a [private branch](https://github.com/Cito/graphql-server-core/tree/use-core-next) for this.

Since this is not fully backward compatible and needs Py 3.6+, this should be done starting with the new major version number 2.0. A branch for maintenance of version 1.x that will be backward compatible should be created from the current master.

But I think we should first discuss the version and naming strategy (graphql-python/graphql-core/issues/241) across projects because this affects serveral other projects, and do some clean-up and maintenance work before we create the new branch (ideally close all pending tickets first).

We should also notify the maintainers of the depending packages of this breaking upgrade.

**Comment by fhennig** [comment]
@Cito hey, is your branch still working?

I too would like to get a new version of this going since graphene has its v3 alpha out as well.

I think bumping to a new major version (because of the breaking changes) would make sense, maybe going straight to a version 3 so it's in line with graphql-core and graphene (both on v3 now).

I'd like to help in getting this done, if possible.

**Comment by Cito** [comment]
Hi @fhenning.

Yes, my branch still uses core-next instead of core v3. The branch and the issue are outdated, core-next has become core v3 and the plan is now to release server-core v3 based on core v3. I just was too busy with day jobs and keeping core v3 up to date. I want to release a core v3.1 beta this week, (based on js v15) and then let's move this forward. It will be probably best to publish an alpha of server-core based on core v3.1 so you can give your feedback before the final release.

Yes, the backend does not exist any more, core v3 uses sync and async only. The backends were mainly necessary to support older Python versions in core v2. server-core uses the `execute()` function which can be called async or sync (if all resolvers are sync). So we don't need a separate API.

**Comment by fhennig** [comment]
Alright, sounds good! Thanks for you work! I'll gladly test the alpha in our codebase.

**Comment by KingDarBoja** [comment]
The migration to graphql-core v3 has been already done along with the integration of the four backends using this library.
