### ISSUE TITLE
tests always installed

### ISSUE THREAD

**Issue by mattiaverga** [graphql-python/graphql-server#74]
Running `pip install graphql-server` will also install tests, but it shouldn't.

**Comment by mattiaverga** [comment]
https://github.com/graphql-python/graphql-server/blob/5b7f5de42efd3d8034b69c9dcc70f506a2247d55/setup.py#L81
should be `exclude=["tests", "tests.*"]`

**Comment by KingDarBoja** [comment]
Released a new beta version v3.0.0b3 with the fix along with the Quart server support.
